CREATE TABLE IF NOT EXISTS `accounts` (
    `id`  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
    `username` VARCHAR(100) NOT NULL,
    `password` VARCHAR(100) NOT NULL,
    `accessType` VARCHAR(25) NOT NULL
)
  ENGINE = INNODB
  DEFAULT CHARACTER SET utf8;